### ISSUE TITLE
Subscriptions and Ring

### ISSUE THREAD

**Issue by nimaai** [walmartlabs/lacinia#299]
Hello

How can one use Lacinia's subscriptions with Ring (+ HttpKit) ?

Does one really need to implement considerable part of the websocket/lacinia/subscriptions mechanism oneself as I am doing here: https://github.com/leihs/leihs-borrow/blob/master/src/dev/playground/ring_ws.clj ?

Thanks

**Comment by hlship** [comment]
We are a small team, and can't support everything. Although I realize that Ring is far more popular that Pedestal, Pedestal is what we use internally. We prefer to only ship code that has seen production at scale at Walmart, and we lack the bandwidth to maintain a parallel version of the lacinia web adapter for Ring, which we don't use in production.

The design of the subscription support inside Lacinia was purposeful, so that it could be implemented in any number of ways for Ring or other web frameworks.  lacinia-pedestal makes use of no secret or privileged aspects of lacinia, which is how it should be.

**Comment by nimaai** [comment]
Sure. Thanks.
