### ISSUE TITLE
Limiting visibility for some schema elements 

### ISSUE THREAD

**Issue by roncodingenthusiast** [walmartlabs/lacinia#348]
Coming from the [ruby implementation](https://graphql-ruby.org), I recently ran into an issue where I wanted to limit certain graphQL elements for some users and dug around the API to see if there was anything like that and didn't find anything. A good example of that is [limiting schema](https://graphql-ruby.org/schema/limiting_visibility.html) in ruby

Would love the ability to limit certain schema elements to only certain type of users for both security reasons and user experience. I would love my API consumers to only see things they have access to and nothing else if that makes sense.

**Comment by hlship** [comment]
This is essentially what directives are for, and the current alpha does a much better job of exposing those directives to the resolvers.  In our own applications, we have a Pedestal interceptor identify the user based on a header or cookie and provide that information in the application context, and individual field resolvers can use that information, as well as directives to indicate necessary authorization roles, to enable or disable their behavior.

Other frameworks in other languages have a specific step where a directive can "wrap" around a provided resolver function; that is not present, as yet, in Lacinia because we have access to the schema as a data structure prior to compilation, and we have higher order functions.  That being said, it could be easier and perhaps we could come up with a mechanism to do a kind of post-walk on the compiled schema to more concisely/easily inject behavior based on directives.

**Comment by hlship** [comment]
There is now more official support for directives, and wrapping resolver functions that have directives, making it possible to roll your own solution.
