### ISSUE TITLE
GraphQL Schema Definition Language to Lacinia EDN

### ISSUE THREAD

**Issue by foomip** [walmartlabs/lacinia#94]
Apologies if this is the wrong place to ask this, but is there a way to convert a GraphQL schema definition into the equivalent Lacinia EDN Schema definition (or vice versa)?

**Comment by bcarrell** [comment]
Not currently -- I'm personally interested in a way to represent the schema in the official text-based schema DSL.  Ultimately a text-based schema would be compiled into the edn version, but it would be nice to be able to represent it (or generate a representation of it if it's written in edn) in text.

**Comment by bcarrell** [comment]
Also, this is definitely the right place to ask questions! :smile:

**Comment by foomip** [comment]
Thanks @bcarrell text-based schema compiled to edn version is exactly what I was looking for as well. Only been doing clojure for a few months now, so not even sure where to start with something like this.

**Comment by hlship** [comment]
The other question is what kinds of extensions to the GraphQL schema format are needed to add meta data such as documentation, and how to identify easily where resolvers go.

**Comment by thorstadt** [comment]
I just opened #113 with a proposed solution.

**Comment by hlship** [comment]
Implemented by #113 .

**Comment by poernahi** [comment]
I tried this feature and ran into a couple of problems. Sorry for the grab-bag format, I have not had the chance to narrow down each problem.

### Use case:

I want to emulate a 3rd party API for compatibility. I used https://github.com/graphql-cli/graphql-cli to dump the schema and feed it into Lacinia and attach resolvers afterwards.

I am assuming graphql-cli (which uses https://github.com/graphql/graphql-js) is a reference implementation. I could not find an official spec for the schema definition language, maybe because it is not yet finalized? https://github.com/facebook/graphql/pull/90

### Issues, in no particular order:

1. Parser expects the whole document to be wrapped in `{}`. graphql-cli produces unwrapped format.

2. By default, the produced schema uses multiline string as docstring. Lacinia's parser does not recognize this and throws exception. There is a switch in `graphql-js` to print docstring as comment, but the default is currently multiline string. Example:

```
"""
Author data
"""
type ArticleAuthor {
  """The author's bio."""
  bio: String

  """The author’s email."""
  email: String!
}
```

3. Directives causes parser to throw. Example:

```
# Declaring a custom directive
directive @someDirective(
  field: String = null
) on FIELD_DEFINITION

# Using a directive
type SomeType {
  someField: FieldType! @deprecated(reason: "Use `fieldTwo` instead")
}
```

4. Default value for input causes parser to throw. Example:

```
input SomeMutationInput {
  aBooleanInput: Boolean = false
}
```

5. `query`,`input` and likely some other keywords are not acceptable argument names. Example:

```
type SomeType {
  fooField(
    query: String
    input: String
  ): FooType
}
```

I could open new issues if that's preferred. Thanks for the library!

**Comment by hlship** [comment]
Please open new issues to track these defects.  Thanks!
